### ISSUE TITLE
Can't get it to work (MariaDB doesn't work, http auth doesn't work :/)

### ISSUE THREAD

**Issue by CwTiruve** [jfroment/seedbox#10]
I've just tried to configure this seedbox on a fresh install of Debian 9.
I've installed dependencies first, no problem.

I've clone the repo, launch the mkdir command and then launch init.sh, no problem.
I've made some edit in .env file,
then I've launch ./update-all.sh, no problem during this process.

**First problem**
Now, I try to launch ./init-setup-nextcloud.sh, but the script output 
`Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused`

The docker nextcloud-db is up, I can bash into docker and connect to mysql without problem. But Nextcloud script can't access, Nextcloud web install can't access either.

**Second problem**
When I try to access to the differents web ui (deluge, radarr, sonarr, etc...), it asks me http auth, when I fill it with the credentials that I have set in .env, the form reappears instantly.

Do you know why I have these problems ? And how to fix it ?

**Comment by jfroment** [comment]
Hello,

For your first problem, is it still happening? I know there have been some issues on the MariaDB images which seems to be fixed now.

For your second problem, that means that the password is incorrect.
The value must not be in clear.
You can generate it by doing:

```sh
openssl passwd -apr1 YOUR_CLEAR_PASSWORD
```

Then, make sure it is surrounded by simples quotes (') in the .env file. To force the changes to be taken into account, just relaunch update-all.sh script.

**Comment by she11sh0cked** [comment]
I get the same error for `init-setup-nextcloud.sh`.  Did you ever find a solution?

**Comment by she11sh0cked** [comment]
I think I found the problem. There seems to be a mixup here:
```diff
docker exec -it -u abc -w /config/www/nextcloud \
  nextcloud bash -c " \
    php occ maintenance:install \
      --database \"mysql\" \
-     --database-host \"${MYSQL_DATABASE}\" \
-     --database-name \"nextcloud-db\" \
+     --database-host \"nextcloud-db\" \
+     --database-name \"${MYSQL_DATABASE}\" \
      --database-user \"${MYSQL_USER}\" \
      --database-pass \"${MYSQL_PASSWORD}\" \
      --admin-user \"${NEXTCLOUD_ADMIN_USER}\" \
      --admin-pass \"${NEXTCLOUD_ADMIN_PASSWORD}\" \
      --admin-email \"${ACME_MAIL}\" \
      --data-dir \"/data\" \
  "
  ```

**Comment by jfroment** [comment]
Oh right, good catch!
In my .env I have the same value for both, so that could explain why I was not impacted myself.
I'm fixing it on dev branch, it will be bundled into the next release on master.

**Comment by CwTiruve** [comment]
I'm glad that you've found some fix for some bugs. Unfortunately, I've installed Windows on my server because I have some obligation for a game server, and I don't want to install Docker on Windows, so I can't use this project anymore. Good luck for the future! :)

**Comment by jfroment** [comment]
No problem, good luck with your setup!
I'm closing this issue, thanks again @she11sh0cked for the fix and @CwTiruve for finding the bug.
