### ISSUE TITLE
Why download volume got mapped to /data/torrents/deluge?

### ISSUE THREAD

**Issue by NyaMisty** [jfroment/seedbox#18]
That's strange, as deluge/jdownloader both used that volume

**Comment by jfroment** [comment]
Yes thats for historical reasons, because at the beginning of this repository there were only Deluge that handled downloads. But for retro-compatibility sake, I kept this name, it should be seen as "Downloads" directory.

**Comment by NyaMisty** [comment]
Got it, I renamed it myself :)
