### ISSUE TITLE
Deluge can't add torrent

### ISSUE THREAD

**Issue by Mrmel94** [jfroment/seedbox#21]
Hi, thanks for this repository is really nice, everything works except deluge, I can't add torrent.
I can connect to the connection manager :

![image](https://user-images.githubusercontent.com/41294396/135048642-8f4a8b86-c3c1-4af3-b94b-e530bbd0e1af.png)

But when I want to add torrent nothing happens : 

![image](https://user-images.githubusercontent.com/41294396/135048853-ee3b4463-0439-4104-aba9-a6820c66508d.png)

docker logs give me that : 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
10:03:05 [WARNING ][deluge.config              :410 ] Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
10:03:05 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
10:03:05 [WARNING ][deluge.config              :410 ] Unable to open config file /config/hostlist.conf: [Errno 2] No such file or directory: '/config/hostlist.conf'
10:03:05 [WARNING ][deluge.config              :475 ] Unable to open config file: /config/hostlist.conf because: [Errno 2] No such file or directory: '/config/hostlist.conf'
10:03:05 [WARNING ][deluge.config              :500 ] Unable to backup old config: [Errno 2] No such file or directory: '/config/hostlist.conf'

Someone has the solution ?

Thanks

**Comment by proppyx** [comment]
Hi, i have the same problem.
i specify the path to config files but i can't add a torrent.
Do you find a solution ?

Thanks
