### ISSUE TITLE
http_auth and Traefik

### ISSUE THREAD

**Issue by awmv** [jfroment/seedbox#22]
Hi there. I really like this repository and I'm trying to get things to work on my machine. I'm facing a problem surrounding Traefik. 
I have access to my subdomains and I checked the credentials in the http_auth file in ~/seedbox/traefik.
`curl -u "username:password" -L http://deluge.domain.com` Response: 401 Unauthorized.

Port 80 gives me SSL_ERROR_INTERNAL_ERROR_ALERT. 

Are further steps necessary to get the reverse proxy to work? Do I have to configure ACME for this? There seems to be an entry for my registrar (Porkbun) on https://go-acme.github.io/lego/dns/porkbun/.

My DNS Forwading on Porkbun:

![image](https://user-images.githubusercontent.com/5155037/137125758-fc2d54c4-f375-47f9-8e60-b59ae659c656.png)

I'm using Ubuntu 20.04.3 LTS and I followed the instructions, so Docker containers are running from root.

Any help is appreciated.

**Comment by awmv** [comment]
My password for the authentication was not escaped 😱💁

I still have the SSL error. I think that has something to do with the env vars that I need to set as params. I'm still on that.

**Comment by jfroment** [comment]
Hello,

Any news on this issue? Can I close it?
