### ISSUE TITLE
Can't connect in HTTP, seems to be a password encryption issue

### ISSUE THREAD

**Issue by Gyrfalc0n** [jfroment/seedbox#27]
Hi,
I can't login with `user:password` in HTTP pages.

I understood that the `HTTP_PASSWORD` field must be encrypted in the `.env` file and put between `'`.

To do this I used the command : 
```echo $(htpasswd -nb user password) | sed -e s/\$/\$\\$/g```

Which generates a hash that I put in the field (only the password part). Then I launch the update with ```sudo ./update-all.sh```, I reboot then I test again. 

The command ```curl user:password -L "http://sonarr.domain.com"``` returns `401 Unauthorized`.

Is there something I did wrong?

**Comment by jfroment** [comment]
Hello,

Users have reported issues with htpasswd method. It might be related to Traefik and how it handles the hashes.
Could you try using the following command to generate the hash?

``openssl passwd -apr1 YOUR_CLEAR_PASSWORD``

Then set the value in .env file using simple quotes and run ``./update-all --no-pull``(--no-pull to speed up the process).

**Comment by Gyrfalc0n** [comment]
Thanks for your reply. I did what you suggested and now http auth is working. Thanks!
