### ISSUE TITLE
.env: line 42: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by liquidpeachy** [jfroment/seedbox#33]
Hi,

Trying to get this working. When I run "./run-seedbox.sh", I get this error:
`[./run-seedbox.sh] ***** Checking environment variables and files... *****
.env: line 42: syntax error near unexpected token `newline'
`

Any idea?

**Comment by alphahyrule** [comment]
I am having the exact same issue. How did you fix it?

**Comment by alphahyrule** [comment]
Update: We gotta remember to remove the <>

**Comment by jfroment** [comment]
Fixed in 2.1 as now the sample .env.sample file is more explicit :)
