### ISSUE TITLE
error looking up volume plugin

### ISSUE THREAD

**Issue by grunt-x57** [jfroment/seedbox#34]
Hello: 

I am having an issue when running ./run-seedbox.sh. "Error response from daemon: create grunt-box_configtraefik: error looking up volume plugin local-persist: plugin "local-persist" not found". 

I followed the steps to enable local-persist and can confirm that it's active in systemctl. However, I'm unsure if I'm missing a key step or if you guys can point me in the right direction.

**Comment by jfroment** [comment]
Hello,

That's strange. Can you try the following command?

docker volume create -d local-persist -o mountpoint=/tmp --name=test
docker volume ls

Also, what versions of docker and compose are you running? And what is the OS? I saw problems running in Windows WSL

**Comment by grunt-x57** [comment]
> 



> Hello,
> 
> That's strange. Can you try the following command?
> 
> docker volume create -d local-persist -o mountpoint=/tmp --name=test docker volume ls
> 
> Also, what versions of docker and compose are you running? And what is the OS? I saw problems running in Windows WSL

I got this:
Error response from daemon: create test: error looking up volume plugin local-persist: plugin "local-persist"

I ran "systemctl status docker-volume-local-persist" and it shows active with this 10 times:
Jul 14 15:14:13 docker-server docker-volume-local-persist[29310]: List Called...    Found 5 volumes
Jul 14 15:19:13 docker-server docker-volume-local-persist[29310]: List Called...    Found 5 volumes


Pop_OS (Ubuntu)
Docker version 20.10.17, build 100c701
docker-compose version 1.29.2, build unknown
Docker Desktop 4.10.1 (82475)

**Comment by jfroment** [comment]
Why are you running Docker Desktop on Linux?
If the docker host is in a VM and the local-plugin is on another host, the two cannot communicate.
Did you try using a native docker installation for Linux?

**Comment by grunt-x57** [comment]
I'm not sure that I understand. The docker host isn't a VM. 

I'll look into other docker installs.

**Comment by jfroment** [comment]
Hello, any news on this? Can I close this issue?

**Comment by Gruntx57** [comment]
Sorry for the delay. User error.

**Comment by grunt-x57** [comment]
Sorry for the delay and I apologize. User error.

**Comment by jfroment** [comment]
No problem. Thanks for the feedback. I'm closing this, please don't hesitate to re-open if required.
