### ISSUE TITLE
Portainer error: Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by notDavid** [jfroment/seedbox#37]
Hi again,

so opening `https://portainer.mydomain.nl/` gives me this error in my webbrowser: `Client sent an HTTP request to an HTTPS server.`

Changing the port from `9443` to `9000` in [the config](https://github.com/jfroment/seedbox/blob/master/config.sample.yaml#L195) fixes it.

Is it a bug or config error on my side?

Thank you!

PS.
I haven't figured out how to set the password yet, whatever i set `PORTAINER_ADMIN_PASSWORD` to i always get `Unauthorized` 🤷🏼‍♂️

**Comment by maximelafarie** [comment]
@notDavid I confirm you it's not a bug, I also had to change the port to `9000`

Thank you for your feedback, it helped me a lot. It definitely should be mentioned in the docs or as comment in the `.env` file.

Again, many thanks 🙏

**Comment by jfroment** [comment]
Sorry for the late fix, indeed some changes in Portainer were breaking, and as I do not use Portainer anymore, I did not encounter the issue myself.
