### ISSUE TITLE
Scratching my head

### ISSUE THREAD

**Issue by burba12** [jfroment/seedbox#39]
I apologize in advance if this is a dumb question but I'm still rather new with some of this and I've been scratching my head at this for hours.

Any idea why I would be seeing this error? I feel like I'm missing something dumb.

xxxxxxx@yyyyyyy:/data/config$ sudo ./run-seedbox.sh 
[./run-seedbox.sh] ***** Checking environment variables and files... *****
[./run-seedbox.sh] ***** Checking configuration... *****
[./run-seedbox.sh] ***** Generating configuration... *****
Error: unknown command "rules.props" for "yq"

**Comment by jfroment** [comment]
Hello,

I'm guessing you're using an old version of ``yq`` on your system, likely < 4.x.
The run-seedbox script needs yq 4+ to be able to decode properties files.

**Comment by burba12** [comment]
You were right, I thought I'd be cheeky and install YQ via apt and ended up with version 4.16. Once I removed it and manually added the binary for 4.3.x it worked like a charm.

Thanks again for everything, magnificent work.

**Comment by jfroment** [comment]
Glad to help!
I'm thinking maybe to add a check on the versions required. Should be easy to add.
