### ISSUE TITLE
Can't reach Deluge when VPN is activate

### ISSUE THREAD

**Issue by Sigri44** [jfroment/seedbox#49]
Hello,

I have installed gluetun-custom to try to add an external VPN on Deluge
It's working, Deluge has the new good external IP (provided by VPN)

But now, if i use radarr/sonarr, they can't reach deluge:8112 (think local_network is disable !?)

I have try to reach the fully TLD:8112 but don't work (think traefik route not allowed, and don't want that)

If i enable VPN on radarr for example, don't work anymore

Do you know how can i access to a local endpoint, when VPN option is enabled ?

Thanks !

**Comment by Sigri44** [comment]
Found !

Need to replace "deluge" host by "gluetun" host, like this configuration :

https://github.com/jfroment/seedbox/blob/3bb3662b147c5515d56242c2857dd4157aba49ea/run-seedbox.sh#L106

**Comment by jfroment** [comment]
Hello, yes exactly, you have to point it to the gluetun container, which is "in front" of deluge when vpn is enabled for this service. It is documented [here](https://github.com/jfroment/seedbox/blob/master/doc/configuration.md#make-the-services-communicate-with-each-other).
