### ISSUE TITLE
[Hotfix] docker compose : 'version' is obsolete

### ISSUE THREAD

**Issue by tblaudez** [jfroment/seedbox#55]
With the new updates for **docker compose**, specifying version is now considered obsolete and will throw a warning when executed :
![image](https://github.com/jfroment/seedbox/assets/39059500/1a1d752f-43b0-4f4e-8d19-566f3cb9adb2)

Removing the top-level `version:` line in the `docker-compose.yaml` file will silence the warning.

**Comment by jfroment** [comment]
Thanks for raising this!
It is now fixed in the ``dev`` branch, which will be merged into ``master`` soon.
