### ISSUE TITLE
[V2.2] Error on FLOOD_PASSWORD

### ISSUE THREAD

**Issue by Sigri44** [jfroment/seedbox#61]
Hello,

Think with new version, problem with the "FLOOD_PASSWORD" variable :
`WARN[0000] The "FLOOD_PASSWORD" variable is not set. Defaulting to a blank string. `

```bash
$ cat .env.custom | grep "flood"
# Flood Password for Deluge RPC daemon
FLOOD_FLOOD_PASSWORD=xxxxxxxxxxxxxxx
#FLOOD_FLOOD_OPTION_HOST=deluge
FLOOD_DELUGE_HOST=deluge
```

**Comment by jfroment** [comment]
Hello, do you confirm that with the new release 2.2.1 it works now?

**Comment by Sigri44** [comment]
> Hello, do you confirm that with the new release 2.2.1 it works now?

Nop, crashed at start, don't understand what's modify on traefik

<img width="721" alt="image" src="https://github.com/user-attachments/assets/bf36f659-eaa2-4f60-9cc7-e3405c0a2aa1">

**Comment by tblaudez** [comment]
Hey there,

I'm hijacking this issue to mention I have the same problem as the gentleman above regarding the `./env/traefik.env` file.
It seems like the file is [trying to source a generated env file](https://github.com/jfroment/seedbox/blob/98cf9e6f0bc87c14e38cffb8dc8badad287b3003/run-seedbox.sh#L320) for the service when said service has a **command** line with environment variables in its docker-compose file.

Looking at the code, I couldn't however find where this file was supposed to be generated for the **traefik** service, which is the first to be configured by the script.

Should I open a new issue for that matter ?

**Comment by jfroment** [comment]
Ok I think the 2.2.1 release came with a bug, although it was supposed to fix some other ones.
Can you try to add a line like:

```yaml
TRAEFIK_DUMMY=dummy
```

in your .env.custom?
It should be sufficient to woarkaround the issue here and give me time to properly fix it.

Sorry for the inconvenience guys.

**Comment by tblaudez** [comment]
I confirm adding such a line in the `.env.custom` file fixes this specific issue.
I don't understand the code fully enough to comprehend what caused this bug and why this actions fixed it.

Thank you for your hard work and your quick reaction Jean, I was really glad to see a new release for this awesome repository.

**Comment by Sigri44** [comment]
> Hello, do you confirm that with the new release 2.2.1 it works now?

Same error at the beginning "flood password not set", and now in logs :
![image](https://github.com/user-attachments/assets/a67ade37-2bc0-40e2-a32e-fd999d6eaeab)

**Comment by tblaudez** [comment]
@Sigri44 Did you edit [this line](https://github.com/jfroment/seedbox/blob/98cf9e6f0bc87c14e38cffb8dc8badad287b3003/.env.sample#L48) in your `.env` file in order to create the **flood** user on Deluge ?

**Comment by Sigri44** [comment]
> @Sigri44 Did you edit [this line](https://github.com/jfroment/seedbox/blob/98cf9e6f0bc87c14e38cffb8dc8badad287b3003/.env.sample#L48) in your `.env` file in order to create the **flood** user on Deluge ?

Yes and same (i already have user in /http/auth, but tried)

**Comment by jfroment** [comment]
That's strange I cannot reproduce your issue.

Can you confirm that you have (after running the script) both:

``services/generated/flood-envfile.yaml`` with content

```yaml
services:
  flood:
    env_file:
      - ./env/flood.env
```

and ``env/flood.env`` with content (at least):

```sh
FLOOD_PASSWORD=yourpassword
```

If yes, can you try to:

* docker rm -f flood
* rm -rf ``CONFIG_DIR_PATH``/flood/*
* ./run-seedbox.sh --no-pull

It should restart Flood service with all remaining data erased. No issue doing this, as Flood's configuration is not that important. You may lose any custom settings related to Flood though, maybe backup them first if you have any.

**Comment by jfroment** [comment]
Also, please [check my comment](https://github.com/jfroment/seedbox/issues/59#issuecomment-2506802782) in issue #59.
Maybe you should remove the line ``FLOOD_DELUGE_HOST=deluge`` from your ``.env.custom`` as this variable is automatically set by the script.

**Comment by Sigri44** [comment]
> That's strange I cannot reproduce your issue.
> 
> Can you confirm that you have (after running the script) both:
> 
> `services/generated/flood-envfile.yaml` with content
> 
> ```yaml
> services:
>   flood:
>     env_file:
>       - ./env/flood.env
> ```
> 
> and `env/flood.env` with content (at least):
> 
> ```shell
> FLOOD_PASSWORD=yourpassword
> ```
> 
> If yes, can you try to:
> 
> * docker rm -f flood
> * rm -rf `CONFIG_DIR_PATH`/flood/*
> * ./run-seedbox.sh --no-pull
> 
> It should restart Flood service with all remaining data erased. No issue doing this, as Flood's configuration is not that important. You may lose any custom settings related to Flood though, maybe backup them first if you have any.

Have follow that, but same.

When i check `/config/auth` into deluge, no flood login.
When i choose true to `FLOOD_AUTOCREATE_USER_IN_DELUGE_DAEMON`, same.
Have try with delete deluge container but same error.
Btw now think with >= 2.2 deluge don't add flood credentials to auth.

**Comment by jfroment** [comment]
Oooh ok I found the bug. It occurs only on fresh installations, that's why I missed it.
Give me 5 minutes to re-edit the 2.2.2 release and I get back to you.

**Comment by jfroment** [comment]
Release [v2.2.2](https://github.com/jfroment/seedbox/releases/tag/v2.2.2) now includes a new fix for your issue.

**Comment by Sigri44** [comment]
Good for me !
