### ISSUE TITLE
Local-persist 

### ISSUE THREAD

**Issue by Qbaakr** [jfroment/seedbox#68]
Hey
at this moment after running the init script the message Curl: (22) The requested URL returned error: 404 :(
Regrats

**Comment by jfroment** [comment]
Hello, thanks for raising this issue. I did not notice that the forked local-persist plugin called from the init script was loading by default the current git release. Anyway, it should work now in the dev branch:

```sh
git checkout dev
git pull
./init.sh
# When done, you can go back to master branch if you prefer more stability
git checkout master
```

Please keep me updated on how it goes so I can close this issue.

**Comment by Qbaakr** [comment]
For this option it is absolutely ok ;)
Tomorrow I will test the rest ;)
Regards
