### ISSUE TITLE
Allow incoming connections outside local network

### ISSUE THREAD

**Issue by darrengiamanti** [jfroment/seedbox#7]
Hello,

I can successfully access the docker services via the registered DNS domain with secure connection (e.g. portainer.mydomain.com)

However, I can only access them from my local network and not from the internet. I have both ports 80 and 443 open on my router. I'm tried to change some configuration on traefik or the docker network but I'm not really sure what to do.

From traefik logs I cannot see anything when I'm trying to access from outside. Where is the problem?
How can I expose the services to external connections?

Thanks!
Darren

**Comment by jfroment** [comment]
Hi,

I think there is a problem with your router. Does your DNS entry points to your public IP address?
If you have nothing shown in Traefik logs when trying to access the service URL, the blocking service is between your device and your router (maybe local DNS config on your device, or DNS provider, or router dns forwarding...)

**Comment by jfroment** [comment]
Hello,

Any news on this issue?
